import Head from "next/head";
import Link from "next/link";
import Header from "./Header";
import { useState } from "react";
function Layout({ children, setSearch, title = "My Crypto Tracker" }) {
  const [theme, setTheme] = useState("light");

  return (
    <div className={theme === "light" ? "bg-light" : "bg-dark text-secondary"}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header setSearch={setSearch} theme={theme} setTheme={setTheme} />
      {children}
    </div>
  );
}
export default Layout;
